# Neden Numpy

In [8]:
a = [1,2,3,4]
b = [2,3,4,5]

In [9]:
import numpy as np

In [10]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5]) 

In [11]:
a * b

array([ 2,  6, 12, 20])

In [2]:
import numpy as np

In [3]:
np.array([3.14,4,2,13], dtype = "int")

array([ 3,  4,  2, 13])

In [4]:
np.zeros(10,dtype = int)  # sıfırlardan oluşan  bir array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.ones((3,5),dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [6]:
np.full((3,5),3) #

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [7]:
np.arange(0,31,3) #0 dan 31 e kadar doğrusal biçimde artacak bir dizi oluşumu

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [8]:
np.linspace(0,1,10) #sıfır ile 1 arasında 10 tane sayi oluşturdu.

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [9]:
np.random.normal(10,4,(3,4)) #ortalaması 10 standart sapması 4 olan 3,4 lük matris

array([[ 7.12380931, 10.23262859, 11.01272773, 13.60672773],
       [10.10488952,  8.48543567,  5.36735076,  6.52124655],
       [ 7.2128871 ,  9.52331778, 17.54529529,  4.95906869]])

In [10]:
np.random.randint(0,10,(3,3))

array([[8, 3, 6],
       [4, 7, 6],
       [5, 7, 4]])