# Yeniden Şekillendirme(Reshaping)

In [6]:
import numpy as np

In [10]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a = np.arange(1,10)

In [15]:
a.ndim

1

In [18]:
b = a.reshape((1,9))

In [19]:
b.ndim

2

# Array Birlestirme (Concatenation)

In [22]:
import numpy as np

In [21]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [24]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [25]:
z = np.array([7,8,9])

In [26]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# iki boyut

In [29]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])

In [30]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [31]:
np.concatenate([a,a],axis = 1) # sutunları birleştir

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])