# Array ayırma(Splitting)

In [1]:
import numpy as np
x = np.array([1,2,3,99,99,3,2,1])

In [3]:
np.split(x,[3,5]) # 3 ve 5 e kadar böl anlamında

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [4]:
a,b,c = np.split(x,[3,5])

In [6]:
a,b,c

(array([1, 2, 3]), array([99, 99]), array([3, 2, 1]))

# iki boyutlu ayırma

In [7]:
m = np.arange(16).reshape(4,4)

In [8]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [10]:
üst,alt = np.vsplit(m,[2])
üst,alt

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]))

In [13]:
sag,sol = np.hsplit(m,[2])
"sag",sag,"sol",sol

('sag',
 array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 'sol',
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]))

# Array sıralama

In [14]:
v = np.array([2,1,4,3,5])

In [15]:
v

array([2, 1, 4, 3, 5])

In [16]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [17]:
v

array([2, 1, 4, 3, 5])

In [18]:
v.sort()#yapıyı bozar.

In [19]:
v

array([1, 2, 3, 4, 5])

# iki boyutlu array sıralama

In [20]:
m = np.random.normal(20,5,(3,3))

In [21]:
m

array([[17.76393756, 22.38541954, 16.50143055],
       [23.84572887, 15.87711335, 26.01483528],
       [15.81078162, 24.22631998, 22.0616746 ]])

In [22]:
np.sort(m,axis =1 )#satırları sıraladı

array([[16.50143055, 17.76393756, 22.38541954],
       [15.87711335, 23.84572887, 26.01483528],
       [15.81078162, 22.0616746 , 24.22631998]])

In [23]:
np.sort(m,axis =0 )#sutunları sıraladı

array([[15.81078162, 15.87711335, 16.50143055],
       [17.76393756, 22.38541954, 22.0616746 ],
       [23.84572887, 24.22631998, 26.01483528]])

# Slicing ile elenanlara erişmek(Array altkümesine erişmek)

In [24]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [25]:
a[0:3]

array([20, 21, 22])

In [26]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [29]:
a[1::2] #ikişer ikişer atlayarak ilerler 1 den başlayarak

array([21, 23, 25, 27, 29])

In [30]:
a[0::3]

array([20, 23, 26, 29])

# iki boyutlu slice islemleri

In [31]:
m = np.random.randint(10,size = (5,5))
m

array([[8, 0, 9, 4, 5],
       [8, 8, 4, 8, 1],
       [3, 7, 3, 7, 6],
       [4, 9, 8, 0, 0],
       [5, 9, 9, 2, 0]])

In [32]:
m[:,0] #tüm satırları seç 0.sutunu getir. ilk sutunu getirdi.

array([8, 8, 3, 4, 5])

In [33]:
m[:,1] #ikinci sutunu getirdi

array([0, 8, 7, 9, 9])

In [34]:
m[0,:] #ilk satır geldi

array([8, 0, 9, 4, 5])

In [35]:
m[0]#ilk satır geldi

array([8, 0, 9, 4, 5])

In [36]:
m[1,:]

array([8, 8, 4, 8, 1])

In [39]:
m[0:2,0:3] #0 dan 2 ye kadar satırları 0dan 3 e kadar sutunları al

array([[8, 0, 9],
       [8, 8, 4]])